export { buildSFCVirtualFiles } from './build'
export { createSvelteCompiler, tryLoadSvelte2Tsx } from './svelte'
export type { Svelte2TsxApi } from './svelte'
export type { SFCCompiler, VirtualFileEntry } from './types'
export { createVueCompiler, tryLoadVueCompiler } from './vue'
export type { VueCompilerApi } from './vue'
