ignoreWorkspaceRootCheck: true
shellEmulator: true

trustPolicy: no-downgrade
packages:
  - playground
  - docs
  - examples/*

trustPolicyIgnoreAfter: 10080
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true
