/**
 * Generated by tsnapi — public API snapshot of `gazania/codegen`
 */
// #region Interfaces
export interface GenerateConfig {
  source: string | GraphQLSchema;
  scalars?: Record<string, string | {
    input: string;
    output: string;
  }>;
  url?: string;
}
// #endregion

// #region Functions
export declare function generate(_: GenerateConfig): string;
export declare function parseSchema(_: string, _?: Pick<GenerateConfig, 'scalars'>): SchemaData;
export declare function printSchema(_: SchemaData, _?: Pick<GenerateConfig, 'scalars' | 'url'>): string;
// #endregion