/**
 * Generated by tsnapi — public API snapshot of `gazania/codegen`
 */
// #region Interfaces
export interface GenerateConfig {
  source: string | GraphQLSchema;
  scalars?: Record<string, string | {
    input: string;
    output: string;
  }>;
  url?: string;
  sourceHash?: string;
}
// #endregion

// #region Functions
export declare function generate(_: GenerateConfig): string;
// #endregion