/**
 * Generated by tsnapi — public API snapshot of `gazania/codegen`
 */
// #region Interfaces
export interface Config {
    schema: SchemaSource;
    output: string;
    scalars?: Record<string, string | {
        input: string;
        output: string;
    }>;
}
export interface GenerateOptions {
    scalars?: Record<string, string | {
        input: string;
        output: string;
    }>;
}
export interface JsonSource {
    json: string;
}
export interface SdlSource {
    sdl: string;
}
export interface UrlSource {
    url: string;
    headers?: Record<string, string>;
    method?: 'GET' | 'POST';
}
// #endregion

// #region Types
export type GetterSource = () => string | Promise<string>;
export type SchemaSource = string | UrlSource | SdlSource | JsonSource | GetterSource;
export type UserConfig = Config | Config[];
// #endregion

// #region Functions
export declare function defineConfig(_: Config): Config;
export declare function generate(_: SchemaSource, _?: GenerateOptions & {
    url?: string;
}): Promise<string>;
export declare function loadSchema(_: SchemaSource): Promise<string>;
export declare function parseSchema(_: string, _?: GenerateOptions): SchemaData;
export declare function printSchema(_: SchemaData, _?: GenerateOptions & {
    url?: string;
}): string;
// #endregion