/**
 * Generated by tsnapi — public API snapshot of `gazania/config`
 */
// #region Interfaces
export interface Config {
  schemas: SchemaConfig[];
  extract?: ExtractConfig;
}
export interface ExtractConfig {
  dir?: string;
  output?: string | null;
  include?: string;
  algorithm?: string;
  tsconfig?: string;
  strict?: boolean;
  noEmit?: boolean;
  ignoreCategories?: SkippedExtractionCategory[];
}
export interface JsonSource {
  json: string;
}
export interface SchemaConfig {
  schema: SchemaLoader;
  output: string;
  scalars?: Record<string, string | {
    input: string;
    output: string;
  }>;
}
export interface SdlSource {
  sdl: string;
}
export interface UrlSource {
  url: string;
  headers?: Record<string, string>;
  method?: 'GET' | 'POST';
}
// #endregion

// #region Types
export type GetterSource = () => string | GraphQLSchema | Promise<string | GraphQLSchema>;
export type SchemaLoader = string | UrlSource | SdlSource | JsonSource | GetterSource;
// #endregion

// #region Functions
export declare function defineConfig(_: Config): Config;
// #endregion