/**
 * Generated by tsnapi — public API snapshot of `gazania/config`
 */
// #region Other
export { Config }
export { defineConfig }
export { GetterSource }
export { JsonSource }
export { SchemaLoader }
export { SdlSource }
export { UrlSource }
export { UserConfig }
// #endregion