/**
 * Generated by tsnapi — public API snapshot of `gazania/extract`
 */
// #region Interfaces
export interface ExtractFS {
  readFile: (_: string) => string | undefined;
  readDirectory: (_: string, _?: readonly string[], _?: readonly string[] | undefined, _?: readonly string[] | undefined, _?: number) => string[];
  fileExists?: (_: string) => boolean;
}
export interface ExtractLogger {
  debug: (..._: any[]) => void;
  warn: (..._: any[]) => void;
  error: (..._: any[]) => void;
}
export interface ExtractManifest {
  operations: Record<string, ManifestEntry>;
  fragments: Record<string, ManifestEntry>;
}
export interface ExtractOptions {
  dir: string;
  include?: string;
  hash: HashFn;
  tsconfig: _$typescript.ParsedCommandLine;
  ignoreCategories?: SkippedExtractionCategory[];
  logger?: ExtractLogger;
  fs?: ExtractFS;
  createHost?: CreateHostFn;
}
export interface ExtractResult {
  manifest: ExtractManifest;
  skipped: SkippedExtraction[];
}
export interface ManifestEntry {
  body: string;
  hash: string;
  loc: SourceLoc;
}
export interface SkippedExtraction {
  file: string;
  line: number;
  reason: string;
  category: SkippedExtractionCategory;
}
// #endregion

// #region Types
export type CreateHostFn = (_: typeof _$typescript, _: _$typescript.System, _: _$typescript.CompilerOptions) => _$typescript.CompilerHost;
export type HashFn = (_: string) => string;
// #endregion

// #region Functions
export declare function extract(_: ExtractOptions): Promise<ExtractResult>;
export declare function parseTSConfig(_: typeof _$typescript, _: string, _: _$typescript.System): _$typescript.ParsedCommandLine;
// #endregion