/**
 * Generated by tsnapi — public API snapshot of `gazania/extract`
 */
// #region Interfaces
export interface ExtractManifest {
  operations: Record<string, ManifestEntry>;
  fragments: Record<string, ManifestEntry>;
}
export interface ExtractOptions {
  dir: string;
  include?: string;
  algorithm?: string;
  cwd?: string;
  tsconfig?: string;
}
export interface ManifestEntry {
  body: string;
  hash: string;
}
// #endregion

// #region Functions
export declare function extract(_: ExtractOptions): Promise<ExtractManifest>;
// #endregion