/**
 * Generated by tsnapi — public API snapshot of `gazania`
 */
// #region Interfaces
export interface BaseObject<Name extends string, Fields extends Record<string, Field<any, any, any>>, Implements extends Record<string, BaseObject<string, any, any>>> extends BaseType<'BaseObject', Name> {
    __define__?: (_: Implements) => Fields;
}
export interface BaseScalar<Name extends string, Output, Input> extends BaseType<'BaseScalar', Name> {
    __define__?: (_: Input) => Output;
}
export interface BaseType<Base extends string, Name extends string> {
    __base__?: () => Base;
    __name__?: () => Name;
}
export interface DefineSchema<Namespace extends Record<string, BaseType<any, any>>> {
    __define__?: () => Namespace;
}
export interface EnumType<Name extends string, Definition extends string> extends BaseScalar<Name, Definition, PackedEnum<Definition>> {
    __type__?: () => 'Enum';
}
export interface Field<Modifier extends string, Type extends BaseType<any, any>, Args extends Record<string, Input<any, any>> = Record<string, never>> {
    __define__?: (_: Args) => [Modifier, Type];
}
export interface FragmentRef<Name extends string, _TypeName extends string> {
    readonly ' $fragmentRefs'?: {
        [K in Name]: true;
    };
}
export interface Gazania {
    query: (_?: string) => OperationBuilderWithoutVars;
    mutation: (_?: string) => OperationBuilderWithoutVars;
    subscription: (_?: string) => OperationBuilderWithoutVars;
    fragment: (_: string) => FragmentBuilder;
    partial: (_: string) => PartialBuilder;
    enum: EnumFunction$1;
}
export interface Input<Modifier extends string, Type extends BaseType<string, string>> {
    __define__?: (_: Modifier, _: Type) => void;
}
export interface InputObjectType<Name extends string, Fields extends Record<string, Input<any, any>>> extends BaseType<'InputObject', Name> {
    __define__?: (_: Fields) => void;
}
export interface InterfaceType<Name extends string, Fields extends Record<string, Field<any, any, any>>, Implements extends Record<string, BaseObject<any, any, any>>> extends BaseObject<Name, Fields, Implements> {
    __type__?: () => 'Interface';
}
export interface ObjectType<Name extends string, Fields extends Record<string, Field<any, any, any>>> extends BaseObject<Name, Fields, Record<string, never>> {
    __type__?: () => 'Type';
}
export interface ScalarType<Name extends string, Output, Input> extends BaseScalar<Name, Output, Input> {
    __type__?: () => 'Scalar';
}
export interface Schemas {
}
export interface TypedDocumentNode<Result = Record<string, any>, Variables = Record<string, any>> extends DocumentNode {
    __apiType?: (_: Variables) => Result;
    __ensureTypesOfVariablesAndResultMatching?: (_: Variables) => Result;
}
export interface TypedGazania<Schema extends DefineSchema<any>> {
    query: (_?: string) => TypedOperationBuilderWithoutVars<Schema, OperationTypeObject<Schema, 'Query'>>;
    mutation: (_?: string) => TypedOperationBuilderWithoutVars<Schema, OperationTypeObject<Schema, 'Mutation'>>;
    subscription: (_?: string) => TypedOperationBuilderWithoutVars<Schema, OperationTypeObject<Schema, 'Subscription'>>;
    fragment: (_: string) => TypedFragmentBuilder<Schema>;
    partial: <Name extends string>(_: Name) => TypedPartialBuilder<Schema, Name>;
    enum: EnumFunction;
}
export interface UnionType<Name extends string, Implements extends Record<string, BaseObject<any, any, any>>> extends BaseObject<Name, Record<string, never>, Implements> {
    __type__?: () => 'Union';
}
export interface UnknownSchema extends Gazania {
}
// #endregion

// #region Types
export type FragmentOf<T> = T extends {
    readonly ' $fragmentOf'?: infer Ref;
} ? Ref : never;
export type ResultOf<T> = T extends TypedDocumentNode<infer Result, any> ? Result : unknown;
export type VariablesOf<T> = T extends TypedDocumentNode<any, infer Variables> ? Variables : unknown;
// #endregion

// #region Functions
export declare function createGazania<T extends string>(_: T): UnknownSchema;
// #endregion

// #region Variables
export declare const gazania: Gazania;
export declare const readFragment: ReadFragmentFn;
// #endregion