/**
 * Generated by tsnapi — public API snapshot of `gazania/transform`
 */
// #region Interfaces
export interface GazaniaTransformOptions {
  include?: (_: string) => boolean;
}
// #endregion

// #region Variables
export declare const esbuild: (options?: GazaniaTransformOptions | undefined) => _$unplugin.EsbuildPlugin;
export declare const farm: (options?: GazaniaTransformOptions | undefined) => JsPlugin;
export declare const GazaniaTransformPlugin: _$unplugin.UnpluginInstance<GazaniaTransformOptions | undefined, boolean>;
export declare const rolldown: (options?: GazaniaTransformOptions | undefined) => _$unplugin.RolldownPlugin<any> | _$unplugin.RolldownPlugin<any>[];
export declare const rollup: (options?: GazaniaTransformOptions | undefined) => Plugin<any> | Plugin<any>[];
export declare const rspack: (options?: GazaniaTransformOptions | undefined) => RspackPluginInstance;
export declare const vite: (options?: GazaniaTransformOptions | undefined) => _$unplugin.VitePlugin<any> | _$unplugin.VitePlugin<any>[];
export declare const webpack: (options?: GazaniaTransformOptions | undefined) => WebpackPluginInstance;
// #endregion

// #region Default Export
declare const _default: _$unplugin.UnpluginInstance<GazaniaTransformOptions | undefined, boolean>;
export default _default
// #endregion